# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Designer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(424, 378)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnAgenda = QtWidgets.QPushButton(self.centralwidget)
        self.btnAgenda.setGeometry(QtCore.QRect(290, 120, 121, 31))
        self.btnAgenda.setStyleSheet("* {\n"
                                     "    background-color: #f44336;\n"
                                     "    color: white;\n"
                                     "    font-weight: bold;\n"
                                     "}")
        self.btnAgenda.setObjectName("btnAgenda")
        self.dtMarca = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dtMarca.setGeometry(QtCore.QRect(10, 80, 112, 20))
        self.dtMarca.setObjectName("dtMarca")
        self.lineFile = QtWidgets.QLineEdit(self.centralwidget)
        self.lineFile.setGeometry(QtCore.QRect(10, 30, 311, 20))
        self.lineFile.setObjectName("lineFile")
        self.tblAgenda = QtWidgets.QTableWidget(self.centralwidget)
        self.tblAgenda.setGeometry(QtCore.QRect(10, 160, 401, 192))
        self.tblAgenda.setObjectName("tblAgenda")
        self.tblAgenda.setColumnCount(2)
        self.tblAgenda.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblAgenda.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAgenda.setHorizontalHeaderItem(1, item)
        self.btnFile = QtWidgets.QPushButton(self.centralwidget)
        self.btnFile.setGeometry(QtCore.QRect(330, 30, 75, 23))
        self.btnFile.setStyleSheet("* {\n"
                                   "    background-color: #1E90FF;\n"
                                   "    color: white;\n"
                                   "    font-weight: bold;\n"
                                   "}")
        self.btnFile.setObjectName("btnFile")
        self.lbArquivo = QtWidgets.QLabel(self.centralwidget)
        self.lbArquivo.setGeometry(QtCore.QRect(10, 10, 47, 13))
        self.lbArquivo.setObjectName("lbArquivo")
        self.lbAgenda = QtWidgets.QLabel(self.centralwidget)
        self.lbAgenda.setGeometry(QtCore.QRect(10, 60, 47, 13))
        self.lbAgenda.setObjectName("lbAgenda")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Agenda 0.1"))
        self.btnAgenda.setText(_translate("MainWindow", "AGENDAR"))
        item = self.tblAgenda.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "PROCESSO"))
        item = self.tblAgenda.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "HORA"))
        self.btnFile.setText(_translate("MainWindow", "ABRIR"))
        self.lbArquivo.setText(_translate("MainWindow", "Arquivo"))
        self.lbAgenda.setText(_translate("MainWindow", "Agenda"))
